version: "3.4"

services:
  starter:
    build:
      context: .
      target: runner_starter
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vactory_http.rule=Host(`vactory.lecontenaire.com`)"
      - "traefik.http.routers.vactory_http.entrypoints=http"
      - "traefik.http.routers.vactory_https.rule=Host(`vactory.lecontenaire.com`)"
      - "traefik.http.routers.vactory_https.entrypoints=https"
      - "traefik.http.routers.vactory_https.tls=true"
      - "traefik.http.routers.vactory_https.tls.certresolver=k8spreprodchallenge"

  ui:
    build:
      context: .
      target: runner_ui
    restart: unless-stopped
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui_vactory_http.rule=Host(`ui.vactory.lecontenaire.com`)"
      - "traefik.http.routers.ui_vactory_http.entrypoints=http"
      - "traefik.http.routers.ui_vactory_https.rule=Host(`ui.vactory.lecontenaire.com`)"
      - "traefik.http.routers.ui_vactory_https.entrypoints=https"
      - "traefik.http.routers.ui_vactory_https.tls=true"
      - "traefik.http.routers.ui_vactory_https.tls.certresolver=k8spreprodchallenge"

  # docs:
  #   build:
  #     context: .
  #     target: runner_docs
  #   restart: unless-stopped
  #   networks:
  #     - internal
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.docs_vactory_http.rule=Host(`docs.vactory.lecontenaire.com`)"
  #     - "traefik.http.routers.docs_vactory_http.entrypoints=http"
  #     - "traefik.http.routers.docs_vactory_https.rule=Host(`docs.vactory.lecontenaire.com`)"
  #     - "traefik.http.routers.docs_vactory_https.entrypoints=https"
  #     - "traefik.http.routers.docs_vactory_https.tls=true"
  #     - "traefik.http.routers.docs_vactory_https.tls.certresolver=k8spreprodchallenge"

  cache:
    image: redis:6.2-alpine
    restart: always
    networks:
      - internal
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

networks:
  internal:
    external: true

volumes:
  cache:
    driver: local
