export const people = [
  {
    id: "1",
    name: "Page 1",
    height: "172",
    mass: "77",
    hair_color: "blond",
    skin_color: "fair",
    eye_color: "blue",
    gender: "male",
  },
  {
    id: "2",
    name: "Page 2",
    height: "167",
    mass: "75",
    hair_color: "n/a",
    skin_color: "gold",
    eye_color: "yellow",
    gender: "n/a",
  },
  {
    id: "3",
    name: "Page 3",
    height: "96",
    mass: "32",
    hair_color: "n/a",
    skin_color: "white, blue",
    eye_color: "red",
    gender: "n/a",
  },
]
