export * from "./paragraphs.controller"
export * from "./paragraphs.container"
export * from "./paragraphs.controller"
export * from "./pargaraphs.multiple"
export * from "./pargaraphs.multiple.tab"
export * from "./pargaraphs.multiple.accordion"
export * from "./pargaraphs.template"
